### ISSUE TITLE
Improve node's start method

### ISSUE THREAD

**Issue by aionick** [aionnetwork/node_test_harness#1]
Currently `node.start()` sleeps for 10 seconds after starting up the node and then the method returns. This is mostly to ensure that the caller waits until the node is up and running before interacting with it too quickly.

What we probably want to do instead is to find some meaningful "event" that signals to us that the node is ready to be used, and to wait for that event to occur - or, after a timeout or any other sort of error, to notify the caller that the `start()` method failed. (We notify them via the `Result` object).

**Comment by aionWilliam** [comment]
Waiting for kernel to start and ready to receive rpc calls, we should wait for the following string from the log: `rpc-server - (UNDERTOW) started on http://127.0.0.1:8545`

**Comment by aionick** [comment]
Perhaps this whole string is not necessary? Really we just want to see that rpc-server has started.
In the future we might want to read the logs to do some verifications, in which case the IP and port may be valuable information to extract. But right now this isn't a concern.

**Comment by aionWilliam** [comment]
Agreed, `rpc-server - (UNDERTOW) started` should be sufficient.

**Comment by aionick** [comment]
The proper solution to this problem is to be able to wait on the "rpc server started" log event or else to time out, and then return from `start()` - but to start watching for this event BEFORE the node even starts.

This requires some refactoring first, and in the interest of meeting our first milestone we will take a bit of a shortcut, and instead not meet the criteria of listening for this event _before_ the node starts, but instead immediately after. This inherits a slight risk that we miss the event, and so we timeout after a few seconds and check if the node is still running. This is assuming that the RPC server is always enabled.
