### ISSUE TITLE
Add other basic RPC methods

### ISSUE THREAD

**Issue by aionick** [aionnetwork/node_test_harness#16]
We should at least support `getBalance` and `getNonce`, but we might also want to look into supporting other useful RPC calls related to transaction receipts or "looking into" blocks.

**Comment by aionWilliam** [comment]
While testing the result of getBalance when sending a negative(BigInteger) transfer, we realize that the actual transfer value was the positive representation of that BigInteger transfer value. Thus, when someone tries to transfer a negative value(BigInteger), the positive representation of that BigInteger will be the transfer value. This should be something handled by the server.

**Comment by aionWilliam** [comment]
Other useful rpc calls we might be interested: `mining`, `coinbase`(miner address), `gasPrice`, `accounts`(list of accounts), `blockNumber`, `getBlockbyNumber`, `getBlockByHash`, `getTransactionReceipt`, `getPeerCount`
