### ISSUE TITLE
Improve Event handling by the NodeListener

### ISSUE THREAD

**Issue by aionWilliam** [aionnetwork/node_test_harness#37]
The `NodeListener` has methods that wait for a specific common `Event` (such as `waitForMinersToStart` and `waitForTransactionToBeProcessed`), but these `Event`s are created internally so users have no access to them. `NodeListener` also has a method `waitForEvent`, which simply waits on a given event the user passes in. We can use this method and deal with events outside of the ``NodeListener`` class.

**Comment by aionWilliam** [comment]
We could provide the convenience of common `Event`s at the event level instead of having the logic in the NodeListener. The class should provide a set of enums for common event calls with corresponding event strings.

**Comment by aionick** [comment]
We should also probably start switching to the less ambiguous way of specifying time outs: `long time, TimeUnit unit`.
