### ISSUE TITLE
Support remaining RPC calls

### ISSUE THREAD

**Issue by aionick** [aionnetwork/node_test_harness#48]
We need to start a checklist here with all of the outstanding RPC calls we have left to support. Ideally, we want to provide support for all of them so that we can test all of them, but we should obviously proceed through this list with some sort of priorities figured out.

**Comment by aionWilliam** [comment]
I am assuming these rpc calls are from the notes in #16 , are there any other one? I currently have `gasPrice` and `coinbase` added.

**Comment by aionick** [comment]
Closing this for now. We do not want to support all RPC calls, and so far we seem to have all of the major calls we need. Perhaps one or two more may be added in the future, but we will deal with them as the needs arise.
