### ISSUE TITLE
Generalize 'wait for transaction to be sealed'

### ISSUE THREAD

**Issue by aionick** [aionnetwork/node_test_harness#5]
Currently we are listening to an event that simply waits for a transaction to be sealed into a block. This isn't really what someone wants though, what we really want here is to wait for a transaction to be "processed". Where processing may means being sealed into a block, or it may mean being rejected and therefore dropped from the network, for example. 

And we should return a result that is adequately descriptive.

**Comment by aionick** [comment]
This will be dependent on the completion of issue #21.

**Comment by aionWilliam** [comment]
In the config file, setting `TX` field to `TRACE` will log the rejection string we are looking for to catch a transaction rejection.  
Rejection detection string: `tx 'transaction hash' is rejected`

**Comment by aionick** [comment]
Does this string already exist or is this something we had to add to our branch in the kernel?

**Comment by aionWilliam** [comment]
we had to make a modification to a tx log call, simply by adding the transaction hash
