### ISSUE TITLE
check status flag on tx receipts

### ISSUE THREAD

**Issue by aion-kelvin** [aionnetwork/node_test_harness#56]
If a transaction does not succeed, leaving a receipt that contains status=0, the test harness should  signal that some error has happened.

Currently, status flag doesn't seem to be checked, so if a test executes a balance transfer and then asserts that sender account balance has changed, the only feedback given by the test case is the failed assertion.  

It would be more meaningful if the test case threw an error (not a failure) if the test case expected the tx to succeed.

**Comment by aionick** [comment]
Closing this. The `TransactionReceipt` class now has a `transactionWasSuccessful()` method that basically reports this status field back to the test. This gives tests an explicit means of checking this.
