### ISSUE TITLE
BalanceTransferTest rust version - checking wrong place for Blockchain print message

### ISSUE THREAD

**Issue by aion-kelvin** [aionnetwork/node_test_harness#61]
In Java kernel, kernel logs are output to stdout.  Blockchain.println goes to stdout also.

In Rust kernel, kernel logs go to stderr.  Blockchain.println goes to stdout.

In the test `org.aion.harness.tests.integ.rust.BalanceTransferTest`, it looks for a kernel log message and also a Blockchain.println in stderr:  
https://github.com/aionnetwork/node_test_harness/blob/master/Tests/test/org/aion/harness/tests/integ/rust/BalanceTransferTest.java#L268

As a result, the test erroneously fails.  It needs to look for the println in stderr instead.

**Comment by aionick** [comment]
I guess the most obvious question is why are logs being written to stderr? And is this something the rust kernel is intentionally doing?

**Comment by aion-kelvin** [comment]
Pretty sure it's intentional.  I don't think it's uncommon for logs of long-running processes to be sent to stderr.

**Comment by aionick** [comment]
That's fair, I suppose we will just want a solution to this that makes further java/rust integration in the harness practical

**Comment by aion-kelvin** [comment]
Yeah I mostly care just because it's a slight hindrance to having one set of tests for both kernels

**Comment by aion-kelvin** [comment]
fixed by https://github.com/aionnetwork/node_test_harness/commit/9793591827e8398cfe26979f91d6ec8de3433aa3 and https://github.com/aionnetwork/node_test_harness/commit/7d36d6d305c7aa9911d075033c95666aa096eda6
